const pathways={C:['Civil engineering','Designing bridges, roads, buildings, water systems, and safer communities.','Try a bridge-load test or sketch a safer route through your school.'],M:['Mechanical engineering','Designing machines, moving parts, sports equipment, vehicles, and robots.','Redesign a paper mechanism, launcher, or small moving model.'],E:['Electrical engineering','Working with circuits, sensors, power, electronics, and communication devices.','Build a simple circuit or map the sensors in an everyday device.'],S:['Computer & software engineering','Creating apps, games, code, AI tools, and systems that process information.','Prototype an app screen, game rule, or short program that solves a real problem.'],Env:['Environmental engineering','Protecting water, air, land, ecosystems, and community health.','Test a simple water-filter idea or audit one way your school could reduce waste.'],B:['Biomedical engineering','Designing technology that helps people stay healthy or recover from injury.','Sketch a more comfortable medical or accessibility tool for a real user.'],Ch:['Chemical & materials engineering','Creating useful substances and improving materials such as batteries, plastics, fabrics, and medicines.','Compare materials for strength, stretch, water resistance, or reuse.'],A:['Aerospace engineering','Designing aircraft, spacecraft, satellites, drones, and exploration technology.','Run a paper-airplane redesign challenge and record what changes its flight.']};
const tracks={
 elementary:{label:"Community Design Quest",games:[
  {title:'A rainy-day problem',scene:'🏫  🌧️  🧒',instruction:'The walk to the school garden gets slippery after rain. Add someone you want your invention to help.',options:[['🧒','Add a friend'],['👵','Add a grandparent'],['🐕','Add a service dog']],feedback:'Added to your story! Engineers begin by caring about the people they help.'},
  {title:'Your design promise',scene:'🌧️  ➜  🌻',instruction:'Choose one promise for your new garden path.',options:[['🛟','Keep it safe'],['♿','Make it easy to use'],['🌎','Care for nature']],feedback:'Promise saved! Every engineering idea has a job it needs to do.'},
  {title:'Open the build box',scene:'🧱  🪵  🟫',instruction:'Choose a material to try in your first path design.',options:[['🧱','Try brick'],['🪵','Try wood'],['🟫','Try stepping stones']],feedback:'Blueprint updated! First ideas are meant to be tested, not perfect.'},
  {title:'Rain test!',scene:'🌧️  🛤️  ✨',instruction:'The rain arrives. Choose your next engineer move.',options:[['🔎','Watch what happens'],['✏️','Change the design'],['🗣️','Listen to the user']],feedback:'That is how engineers grow an idea: test, listen, and improve.'}
 ],result:{title:"You are a Community Engineer!",text:"You helped someone, chose what mattered, made an idea, and improved it. That is real engineering—not getting one perfect answer the first time.",next:["Draw your garden path or another helpful invention.","Circle one thing it must do: be safe, easy to use, fun, or kind to nature.","Tell someone what you would test and change next."]}},
 middle:{label:'Grades 6–8 · Engineering Explorer',questions:[
 ['If you could fix or improve one thing at your school, what would it be?',[['A cracked sidewalk or unsafe stairwell','C'],['A recycling-bin system that actually gets used','Env'],['A vending machine or locker that keeps jamming','M'],['An app that helps students find classrooms or buses','S']]],
 ['Which class project would you be most excited to build?',[['A tower or bridge from spaghetti or popsicle sticks','C'],['A little car or catapult that actually moves','M'],['A blinking light or simple alarm circuit','E'],['A short animation or mini-game on a computer','S']]],
 ['Your backpack strap keeps snapping. What part interests you most?',[['Why the shape of the strap makes it rip','M'],['Whether a different fabric would stretch less','Ch'],['A tiny sensor that beeps before it breaks','E'],['Redesigning the whole bag to feel better on someone’s back','B']]],
 ['Which kind of puzzle is most fun for you?',[['Taking apart a toy to see how the gears move','M'],['Following clues in order to crack a code','S'],['Untangling a mess of wires or lights','E'],['Figuring out the best route on a map','C']]],
 ['Your neighborhood keeps flooding after big storms. What would you work on?',[['Better drains, sidewalks, or a small bridge','C'],['Testing whether floodwater is safe or dirty','Env'],['A sensor that warns when water is rising','E'],['Using past-storm data to predict flooding','S']]],
 ['Which invention would make you most proud to help build?',[['A robot arm that helps sort recycling','M'],['A wearable that reminds someone to take medicine','B'],['A safer battery for phones','Ch'],['A tiny satellite that photographs Earth','A']]],
 ['Your gaming controller or remote stops working. What do you check first?',[['Whether a wire or battery is loose','E'],['Whether the game or app has a glitch','S'],['Whether a button or gear is stuck','M'],['Whether the plastic case is cracked or worn out','Ch']]],
 ['Your school wants a new outdoor hangout space. What part excites you most?',[['Planning paths, benches, and ramps','C'],['Picking plants that need little water','Env'],['Adding solar-powered lights','E'],['Designing a touchscreen kiosk with school information','S']]],
 ['Which everyday question would you most want to answer?',[['How do buildings stay standing in an earthquake?','C'],['How can we get plastic out of the ocean?','Env'],['How does a smartwatch count a heartbeat?','B'],['How does a heavy plane stay in the air?','A']]],
 ['In a group project, which role would you choose?',[['Sketch the design and plan how it should work','C'],['Build the model and make sure it moves','M'],['Write the steps or organize the group’s data','S'],['Check how the finished design affects people or nature','Env']]],
 ['If you had a box of craft and hardware supplies, what would you build?',[['A small car, ramp, or launcher','M'],['A circuit that lights up or makes noise','E'],['A model rocket or glider','A'],['Something stretchy, waterproof, or color-changing','Ch']]],
 ['Which result would feel most satisfying to see?',[['A tower holding far more weight than expected','C'],['Your code running exactly as planned','S'],['A device that helps someone move or feel better','B'],['A park or stream looking cleaner than before','Env']]],
 ['Your school’s sports teams ask for help. Which problem would you pick?',[['Designing a safer helmet or knee pad','B'],['Finding a better material for running-shoe soles','Ch'],['Building a camera setup that tracks player speed','E'],['Building an app that tracks team statistics','S']]],
 ['Which tool would you most want to learn?',[['A 3D printer or basic building kit','M'],['A coding environment or game maker','S'],['A circuit kit with wires, batteries, and lights','E'],['A model-building or map-drawing tool','C']]],
 ['Which topic would you pick to learn more about?',[['How engines, machines, and motion work','M'],['How electricity, magnets, and signals work','E'],['How the human body and medical tools work','B'],['How weather, water, and ecosystems work','Env']]],
 ['A delivery must reach a place with no roads. Which solution sounds most fun?',[['Designing a path or small bridge','C'],['Building a drone to fly it in','A'],['Programming the drone’s flight path','S'],['Designing lightweight packaging so nothing breaks','Ch']]],
 ['Pick a challenge for a school invention fair.',[['Make a classroom use less electricity','E'],['Make a cafeteria produce less trash','Env'],['Make a home task easier with a machine','M'],['Make a medical tool more comfortable for kids','B']]],
 ['Fast forward ten years: which project would you be most excited to work on?',[['A new stadium, bridge, or water park','C'],['A robot or electric go-kart','M'],['An app or game that makes people’s lives easier','S'],['A plane, drone, spacecraft, or flying car','A']]]
 ]},
 high:{label:'Grades 9–12 · Pathway Finder',questions:[
 ['A growing city needs to improve daily life. Which challenge interests you most?',[['Planning safer transit, streets, and public spaces','C'],['Reducing urban heat and stormwater runoff','Env'],['Designing connected traffic signals','E'],['Building a data tool for city services','S']]],
 ['For a Mars mission, which system would you most want to work on?',[['A lightweight landing structure','A'],['A rover’s moving arm and wheels','M'],['Power generation and communication','E'],['Software that navigates the mission','S']]],
 ['A hospital wants to reduce patient stress. What would you investigate?',[['A more comfortable wearable monitor','B'],['A scheduling system that predicts wait times','S'],['Materials that make equipment easier to clean','Ch'],['A reliable sensor that catches warning signs','E']]],
 ['A campus wants longer-lasting phone charging. What is the most interesting problem?',[['Improving battery chemistry','Ch'],['Designing a safer charging circuit','E'],['Reducing energy waste in the building','Env'],['Building a compact charging mechanism','M']]],
 ['Which transportation challenge would you choose?',[['Designing a bridge that handles heavier traffic','C'],['Improving an electric vehicle drivetrain','M'],['Creating vehicle-to-vehicle communication','E'],['Writing software that optimizes routes','S']]],
 ['After a hurricane, what system would you most want to improve?',[['Resilient roads, drainage, and shelters','C'],['Drones that inspect hard-to-reach areas','A'],['Emergency power and warning sensors','E'],['A map that helps people find safe routes','S']]],
 ['A factory is making too many defective products. What would you focus on?',[['Improving the moving parts on a production line','M'],['Using sensors to find problems earlier','E'],['Writing software to identify patterns in the data','S'],['Choosing a material that is more consistent','Ch']]],
 ['A town’s drinking-water source is under stress. What would you tackle?',[['Protecting the watershed from pollution','Env'],['Designing a stronger treatment process','Ch'],['Upgrading pipes and pumping systems','C'],['Installing sensors that report water quality','E']]],
 ['A farm wants to grow more food with fewer resources. Which idea stands out?',[['Designing an irrigation plan that saves water','Env'],['Building a machine that sorts crops','M'],['Using sensors to measure soil conditions','E'],['Creating software that predicts harvest needs','S']]],
 ['Which accessibility project feels most meaningful?',[['A prosthetic or rehabilitation device','B'],['A smoother wheelchair ramp and route','C'],['A control system that helps a chair move safely','E'],['An app that maps accessible entrances','S']]],
 ['A community wants to prepare for hotter summers. What would you study?',[['Cooler roofs and shade structures','C'],['Air quality and neighborhood heat patterns','Env'],['Efficient cooling controls','E'],['A dashboard that shares heat-risk information','S']]],
 ['What part of an autonomous vehicle interests you most?',[['The code that makes driving decisions','S'],['The cameras, radar, and electronics','E'],['The steering, braking, and moving hardware','M'],['How it safely travels on roads and intersections','C']]],
 ['A medical team needs faster ways to analyze images. What would you explore?',[['A tool that helps doctors spot patterns','S'],['A sensor that captures clearer signals','E'],['A material for safer imaging equipment','Ch'],['A device designed around patient comfort','B']]],
 ['A product must survive rain, impacts, and heat. What is your first focus?',[['Testing new coatings or composite materials','Ch'],['Redesigning the mechanism that opens and closes','M'],['Reducing its environmental footprint','Env'],['Making the interface easier for people to use','B']]],
 ['A satellite team is planning an Earth-observation mission. Which role fits best?',[['Designing its orbit and flight systems','A'],['Building the power and communications hardware','E'],['Writing code to process satellite images','S'],['Choosing materials that survive extreme temperatures','Ch']]],
 ['A school is building a new science wing. What would you lead?',[['The foundation, structure, and accessible layout','C'],['The ventilation and energy systems','Env'],['The electrical distribution and lab controls','E'],['The building-management software','S']]],
 ['Which clean-energy challenge would you rather solve?',[['Making a grid more stable during peak demand','E'],['Planning where solar and wind projects should go','C'],['Measuring environmental impacts of new projects','Env'],['Writing software that forecasts energy use','S']]],
 ['A robotics team needs a better competition robot. What would you own?',[['The arms, drivetrain, and mechanical motion','M'],['The sensors and control electronics','E'],['The code that plans its actions','S'],['A grip designed to handle objects safely','B']]],
 ['A company wants to make a household cleaner safer and less wasteful. Which question comes first?',[['How can the formula work with less harmful chemistry?','Ch'],['How can its packaging be easier to recycle?','Env'],['How can a dispenser deliver the right amount?','M'],['How can the device sense when it is empty?','E']]],
 ['Which aviation problem would you most want to investigate?',[['How aircraft wings and structures handle loads','A'],['How engines use fuel more efficiently','M'],['How flight-control systems communicate','E'],['How software plans safer flight paths','S']]],
 ['A physical therapist wants a better way to track recovery. What would you design?',[['A wearable that measures movement safely','B'],['A device that supports repeated exercises','M'],['An app that shows progress over time','S'],['A fabric that is flexible and comfortable to wear','Ch']]],
 ['A flood-prone region needs a long-term plan. What would you contribute?',[['A model for drainage, levees, and road elevations','C'],['A plan to protect wetlands and water quality','Env'],['Software that predicts flood risk from data','S'],['Sensors that report river levels in real time','E']]],
 ['Which connected-device problem is most interesting?',[['Protecting the software from security risks','S'],['Designing low-power electronics','E'],['Making the enclosure durable and repairable','M'],['Creating a health-monitoring feature for users','B']]],
 ['A delivery company wants packaging that creates less waste. What would you test?',[['A new reusable or compostable material','Ch'],['A design that uses less packaging overall','Env'],['A machine that packs items more reliably','M'],['A tracking system that reduces failed deliveries','S']]],
 ['A public-health department needs better community data. What would you build?',[['A device that makes testing more comfortable','B'],['A model that identifies health trends','S'],['Sensors that monitor a local environmental exposure','E'],['A safer water or air system for neighborhoods','Env']]],
 ['A drone company wants to inspect power lines. Which challenge would you choose?',[['Keeping the drone stable in wind','A'],['Designing its cameras and electrical systems','E'],['Building a light but durable frame','M'],['Writing software that detects line damage','S']]],
 ['A building must use less energy and last for decades. What interests you most?',[['Designing its structural system for a changing climate','C'],['Selecting low-carbon, durable materials','Ch'],['Controlling lighting and power use intelligently','E'],['Measuring its water and environmental performance','Env']]],
 ['Your capstone team has a huge data set from a real product. What is your role?',[['Finding useful patterns with code','S'],['Connecting the data to a physical system model','C'],['Testing how a moving mechanism affects the results','M'],['Evaluating the environmental tradeoffs','Env']]],
 ['A startup is redesigning a health product. What would you be most excited to improve?',[['How it fits and feels for the person using it','B'],['The material’s safety and durability','Ch'],['The mechanism that makes it easy to use','M'],['The electronics that collect useful information','E']]],
 ['During an internship, which project would you choose first?',[['Inspecting a bridge or transportation project','C'],['Building and testing a machine prototype','M'],['Debugging a sensor board or power system','E'],['Developing a feature for a software product','S']]],
 ['For a final engineering project, what outcome would motivate you most?',[['A safer, more resilient community system','C'],['A machine that solves a hands-on problem','M'],['A digital tool people can use every day','S'],['A vehicle or system that explores beyond Earth','A']]],
 ['Which research question sounds most compelling?',[['How can structures stay safe during earthquakes?','C'],['How can robots work safely beside people?','M'],['How can computers learn from real-world data?','S'],['How can spacecraft travel farther with limited power?','A']]],
 ['A school district wants safer buses. What would you work on?',[['A traffic-flow and pickup-area redesign','C'],['A system that tracks vehicle maintenance','M'],['Sensors that alert drivers to hazards','E'],['Software that plans more efficient routes','S']]],
 ['A company needs a new material for a medical device. What matters most to you?',[['How the material works with the human body','B'],['How its chemical properties can be tuned','Ch'],['How it can be manufactured reliably','M'],['How sensors could monitor it in use','E']]],
 ['A coastal community is planning for sea-level rise. What contribution fits you?',[['Designing stronger seawalls and elevated infrastructure','C'],['Restoring ecosystems that reduce flood impacts','Env'],['Installing sensor networks for tides and storms','E'],['Creating models that show long-term risk','S']]],
 ['Which space technology would you most want to prototype?',[['A small satellite or flight system','A'],['A robotic arm for a rover','M'],['A power system for a remote mission','E'],['Software that guides a spacecraft autonomously','S']]],
 ['A product team is trying to cut its carbon footprint. Which work would you choose?',[['Redesigning the product with lower-impact materials','Ch'],['Measuring emissions across the product life cycle','Env'],['Making its mechanical system use less energy','M'],['Adding controls that eliminate wasted power','E']]],
 ['A research lab needs to collect data from a remote river. What would you design?',[['A structure that safely supports the equipment','C'],['A water-quality sampling system','Env'],['A solar-powered sensor station','E'],['Software that turns measurements into useful forecasts','S']]],
 ['Which engineering problem would you be happiest to solve after college?',[['Making buildings and transportation safer for more people','C'],['Creating a device that improves someone’s health','B'],['Building technology that protects ecosystems','Env'],['Designing aircraft or spacecraft that expand exploration','A']]],
 ['A company wants to make its supply chain more reliable. Which piece would you improve?',[['The roads, ports, and warehouses that move products','C'],['The machines that sort and package items','M'],['The tracking systems that report where items are','S'],['The battery and sensor systems inside smart shipments','E']]]
 ]}
};
const dialog=document.querySelector('#quiz-dialog'),content=document.querySelector('#quiz-content');let current,step,choices;
function showQuestion(){if(current==='elementary')return showElementaryGame();const[question,answers]=tracks[current].questions[step],progress=`<p class="quiz-progress">${tracks[current].label} · ${step+1} of ${tracks[current].questions.length}</p>`;content.innerHTML=`<div class="quiz-wrap">${progress}<h2 id="quiz-title">${question}</h2><div class="answers">${answers.map(([answer,category])=>`<button class="answer" data-category="${category}">${answer}</button>`).join('')}</div></div>`;content.querySelectorAll('.answer').forEach(button=>button.addEventListener('click',()=>{choices.push(button.dataset.category);step++;step<tracks[current].questions.length?showQuestion():showResult()}))}
function showElementaryGame(){const game=tracks.elementary.games[step];content.innerHTML=`<div class="quiz-wrap"><div class="blueprint-bar"><span>My garden-path blueprint</span><span>${['Meet','Promise','Build','Improve'].map((x,i)=>`<b class="${i<=step?'done':''}">${i+1}</b>`).join('')}</span></div><h2 id="quiz-title">${game.title}</h2><div class="game-stage"><div class="game-scene">${game.scene}</div><p class="game-instruction">${game.instruction}</p><div class="game-options">${game.options.map((option,index)=>`<button class="game-choice" data-game-choice="${index}"><span class="emoji">${option[0]}</span>${option[1]}</button>`).join('')}</div><p class="game-feedback" aria-live="polite"></p></div></div>`;content.querySelectorAll('[data-game-choice]').forEach(button=>button.addEventListener('click',()=>{choices.push(Number(button.dataset.gameChoice));button.classList.add('win');content.querySelector('.game-feedback').textContent='✨ '+game.feedback;content.querySelectorAll('[data-game-choice]').forEach(x=>x.disabled=true);setTimeout(()=>{step++;step<4?showElementaryGame():showResult()},900)}))}
function showResult(){const r=tracks[current].result;let title=r?.title,text=r?.text,next=r?.next;if(current!=='elementary'){const scores=Object.fromEntries(Object.keys(pathways).map(category=>[category,0]));choices.forEach(category=>scores[category]++);const top=Object.entries(scores).filter(([,score])=>score>0).sort((a,b)=>b[1]-a[1]||a[0].localeCompare(b[0])).slice(0,3).map(([category])=>pathways[category]);title='You may enjoy exploring these engineering areas.';text='Your choices point to more than one possible direction. Engineering is multidisciplinary, so this is a starting point for exploration—not a recommendation or permanent label.';next=top.map(([name,description,mission])=>`<strong>${name}:</strong> ${description} <em>Try this:</em> ${mission}`)}content.innerHTML=`<div class="quiz-wrap"><p class="result-tag">${current==='elementary'?'⭐ Mission reward':'Your exploration starter'}</p><h2 id="quiz-title">${title}</h2><p class="result-text">${text}</p><h3>${current==='elementary'?'Your next mission':'Your top areas to explore'}</h3><ul class="next-list">${next.map(x=>`<li>${x}</li>`).join('')}</ul>${current==='high'?'<a class="button button-primary" href="https://engineering.purdue.edu/Engr/Academics/Undergraduate" target="_blank" rel="noopener">Explore Purdue Engineering</a>':''}<br><button class="button restart" id="restart">Try another path</button><p class="disclaimer">This is an exploration tool, not academic advising or a major recommendation.</p></div>`;document.querySelector('#restart').addEventListener('click',()=>dialog.close())}
document.querySelectorAll('.track-card').forEach(card=>card.addEventListener('click',()=>{if(card.dataset.track==='elementary'){window.location.href='elementary.html';return}current=card.dataset.track;step=0;choices=[];showQuestion();dialog.showModal()}));document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
